In [1]:
import pandas as pd
import numpy as np

In [2]:
Dataset = pd.read_excel("University_Clustering.xlsx")

In [3]:
Dataset.describe()

               SAT       Top10     Accept   SFRatio      Expenses   GradRate
count    25.000000   25.000000  25.000000  25.00000     25.000000  25.000000
mean   1266.440000   76.480000  39.200000  12.72000  27388.000000  86.720000
std     108.359771   19.433905  19.727308   4.06735  14424.883165   9.057778
min    1005.000000   28.000000  14.000000   6.00000   8704.000000  67.000000
25%    1240.000000   74.000000  24.000000  11.00000  15140.000000  81.000000
50%    1285.000000   81.000000  36.000000  12.00000  27553.000000  90.000000
75%    1340.000000   90.000000  50.000000  14.00000  34870.000000  94.000000
max    1415.000000  100.000000  90.000000  25.00000  63575.000000  97.000000

In [4]:
Dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Univ      25 non-null     object
 1   State     25 non-null     object
 2   SAT       25 non-null     int64
 3   Top10     25 non-null     int64
 4   Accept    25 non-null     int64
 5   SFRatio   25 non-null     int64
 6   Expenses  25 non-null     int64
 7   GradRate  25 non-null     int64
dtypes: int64(6), object(2)
memory usage: 1.4+ KB

In [5]:
# PCA is only for numeric data, so remove  non-numeric data

data = Dataset.drop(['State'], axis = 1)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Univ      25 non-null     object
 1   SAT       25 non-null     int64
 2   Top10     25 non-null     int64
 3   Accept    25 non-null     int64
 4   SFRatio   25 non-null     int64
 5   Expenses  25 non-null     int64
 6   GradRate  25 non-null     int64
dtypes: int64(6), object(1)
memory usage: 1.3+ KB

In [9]:
from sklearn.decomposition import PCA
# import PCA packages

In [11]:
import matplotlib.pyplot as plt
from sklearn.preprocessing import scale

#scale func() is used for standardization

In [13]:
# lets have only numeric data in dataset
num_data = data.iloc[:,1:]

In [14]:
data_nor = scale(num_data)

In [15]:
data_nor

array([[ 0.41028362,  0.6575195 , -0.88986682,  0.07026045, -0.33141256,
         0.82030265],
       [ 1.39925928,  1.23521235, -0.73465749, -1.68625071,  2.56038138,
        -0.64452351],
       [-0.06065717, -0.76045386,  1.02438157, -0.93346022, -0.16712136,
        -1.65863393],
       [ 0.41028362, -0.02520842, -0.78639393, -0.18066972,  0.29164871,
         0.14422904],
       [ 0.12771914,  0.34241431, -0.32076595,  0.07026045, -0.39084607,
         0.36958691],
       [ 0.69284809,  0.6575195 , -0.83813038, -0.68253005,  0.33778044,
         0.93298158],
       [ 0.4573777 ,  0.71003703, -0.47597528, -0.18066972,  0.29695528,
         0.93298158],
       [-0.10775125, -0.13024348, -0.78639393, -0.18066972, -0.51381683,
         0.59494478],
       [ 1.25797704,  0.76255456, -1.30375836, -0.43159988,  0.85874344,
         1.15833946],
       [ 0.36318954, -0.07772595,  0.24833493, -1.43532055,  2.21481798,
         0.0315501 ],
       [ 1.06960072,  0.92010716, -0.47597528, -0.68253005,  0.52938275,
         0.48226584],
       [-0.06065717,  0.44744937, -0.01034729, -0.43159988,  0.04698077,
         0.25690797],
       [-0.10775125,  0.23737924,  0.14486204,  0.07026045, -0.86787073,
         0.82030265],
       [-1.7466252 , -2.02087462,  0.76569936,  1.32491127, -1.21718409,
        -0.75720245],
       [ 1.02250664,  0.76255456, -1.30375836, -1.18439038,  0.20037583,
         0.93298158],
       [-2.46245521, -2.54604994,  2.6282113 ,  1.57584144, -1.29635802,
        -1.99667073],
       [ 0.88122441,  0.71003703, -0.9933397 , -0.18066972,  0.64117435,
         0.70762371],
       [-1.8031381 , -1.44318177,  1.43827311,  3.08142243, -1.32197103,
        -2.22202861],
       [-0.24903349,  0.97262469,  0.04138915,  1.07398111, -0.86659715,
        -0.98256032],
       [ 0.2219073 , -0.07772595,  0.55875358,  0.07026045,  0.77772991,
         0.0315501 ],
       [-0.81416244, -0.60290126,  1.49000956,  0.82305094, -0.84324827,
        -0.19380777],
       [ 0.17481322,  0.18486171, -0.16555662, -0.43159988,  0.01167444,
         0.36958691],
       [-0.39031573,  0.02730912,  0.24833493,  0.32119061, -0.99331788,
         0.59494478],
       [-1.70894994, -1.91583956,  1.541746  ,  0.57212078, -1.09888311,
        -1.77131286],
       [ 1.02250664,  0.97262469, -1.04507615, -0.43159988,  1.14098185,
         1.04566052]])

In [22]:
pca = PCA(n_components = 6)
# original dataset consists of 6 colums, so components is 6
pca_values = pca.fit_transform(data_nor)

In [23]:
pca_values

array([[-1.00987445e+00, -1.06430962e+00,  8.10663051e-02,
         5.69506350e-02, -1.28754245e-01, -3.46496377e-02],
       [-2.82223781e+00,  2.25904458e+00,  8.36828830e-01,
         1.43844644e-01, -1.25961913e-01, -1.80703168e-01],
       [ 1.11246577e+00,  1.63120889e+00, -2.66786839e-01,
         1.07507502e+00, -1.91814148e-01,  3.45679459e-01],
       [-7.41741217e-01, -4.21874699e-02,  6.05008649e-02,
        -1.57208116e-01, -5.77611392e-01,  1.09163092e-01],
       [-3.11912064e-01, -6.35243572e-01,  1.02405189e-02,
         1.71363672e-01,  1.27261287e-02, -1.69212696e-02],
       [-1.69669089e+00, -3.44363283e-01, -2.53407507e-01,
         1.25643278e-02, -5.26606002e-02, -2.71661600e-02],
       [-1.24682093e+00, -4.90983662e-01, -3.20938196e-02,
        -2.05643780e-01,  2.93505340e-01, -7.80119838e-02],
       [-3.38749784e-01, -7.85168589e-01, -4.93584829e-01,
         3.98563085e-02, -5.44978619e-01, -1.55371653e-01],
       [-2.37415013e+00, -3.86538883e-01,  1.16098392e-01,
        -4.53365617e-01, -2.30108300e-01,  2.66983932e-01],
       [-1.40327739e+00,  2.11951503e+00, -4.42827141e-01,
        -6.32543273e-01,  2.30053526e-01, -2.35615124e-01],
       [-1.72610332e+00,  8.82371161e-02,  1.70403663e-01,
         2.60901913e-01,  2.33318380e-01,  2.38968449e-01],
       [-4.50857480e-01, -1.11329480e-02, -1.75746046e-01,
         2.36165626e-01,  2.63250697e-01, -3.14843521e-01],
       [ 4.02381405e-02, -1.00920438e+00, -4.96517167e-01,
         2.29298758e-01,  4.48031921e-01,  4.93921533e-03],
       [ 3.23373034e+00, -3.74580487e-01, -4.95372816e-01,
        -5.21237711e-01, -6.39294809e-01, -9.00477852e-02],
       [-2.23626502e+00, -3.71793294e-01, -3.98993653e-01,
         4.06966479e-01, -4.16760680e-01,  5.06186327e-02],
       [ 5.17299212e+00,  7.79915346e-01, -3.85912331e-01,
        -2.32211711e-01,  1.79286976e-01, -3.09046943e-02],
       [-1.69964377e+00, -3.05597453e-01,  3.18507851e-01,
        -2.97462682e-01, -1.63424678e-01,  1.14422592e-01],
       [ 4.57814600e+00, -3.47591363e-01,  1.49964176e+00,
        -4.54251714e-01, -1.91141971e-01,  1.04149297e-01],
       [ 8.22603117e-01, -6.98906146e-01,  1.42781145e+00,
         7.60778800e-01,  1.84260335e-01, -2.51103268e-01],
       [-9.77621343e-02,  6.50446454e-01,  1.00508440e-01,
        -5.00097185e-01,  4.87217823e-01,  2.19242132e-01],
       [ 1.96318260e+00, -2.24767561e-01, -2.55881433e-01,
        -4.84741049e-02,  8.22745655e-01,  1.52246521e-01],
       [-5.42288939e-01, -7.95888376e-02, -3.05393475e-01,
         1.31698758e-01,  5.27399148e-02, -3.67264440e-02],
       [ 5.32220920e-01, -1.01716720e+00, -4.23716362e-01,
         1.69535706e-01,  3.57813210e-01, -6.60989993e-02],
       [ 3.54869664e+00,  7.78461666e-01, -4.49363319e-01,
         3.23678618e-01, -3.58332564e-01, -7.74564151e-02],
       [-2.30590032e+00, -1.17704318e-01,  2.53988661e-01,
        -5.16183372e-01,  5.58940129e-02, -1.07932007e-02]])

In [36]:
var = pca.explained_variance_ratio_
var

array([0.76868084, 0.13113602, 0.04776031, 0.02729668, 0.0207177 ,
       0.00440844])

In [25]:
pca.components_

array([[-0.45774863, -0.42714437,  0.42430805,  0.39064831, -0.36252316,
        -0.37940403],
       [ 0.03968044, -0.19993153,  0.32089297, -0.43256441,  0.6344864 ,
        -0.51555367],
       [ 0.1870388 ,  0.49780855, -0.15627899,  0.60608085,  0.20474114,
        -0.53247261],
       [ 0.13124033,  0.37489567,  0.0612872 , -0.50739095, -0.62340055,
        -0.43863341],
       [ 0.02064583,  0.4820162 ,  0.8010936 ,  0.07682369,  0.07254775,
         0.33810965],
       [ 0.8580547 , -0.39607492,  0.21693361,  0.1720479 , -0.17376309,
        -0.00353754]])

In [26]:
pca.components_[0]

array([-0.45774863, -0.42714437,  0.42430805,  0.39064831, -0.36252316,
       -0.37940403])

In [27]:
# cumulative variance 

var1 = np.cumsum(np.round(var, decimals=4)*100)
var1

array([ 76.87,  89.98,  94.76,  97.49,  99.56, 100.  ])

In [30]:
pca_values

# make the pca_values into a dataframe

pca_data = pd.DataFrame(pca_values)
pca_data

           0         1         2         3         4         5
0  -1.009874 -1.064310  0.081066  0.056951 -0.128754 -0.034650
1  -2.822238  2.259045  0.836829  0.143845 -0.125962 -0.180703
2   1.112466  1.631209 -0.266787  1.075075 -0.191814  0.345679
3  -0.741741 -0.042187  0.060501 -0.157208 -0.577611  0.109163
4  -0.311912 -0.635244  0.010241  0.171364  0.012726 -0.016921
5  -1.696691 -0.344363 -0.253408  0.012564 -0.052661 -0.027166
6  -1.246821 -0.490984 -0.032094 -0.205644  0.293505 -0.078012
7  -0.338750 -0.785169 -0.493585  0.039856 -0.544979 -0.155372
8  -2.374150 -0.386539  0.116098 -0.453366 -0.230108  0.266984
9  -1.403277  2.119515 -0.442827 -0.632543  0.230054 -0.235615
10 -1.726103  0.088237  0.170404  0.260902  0.233318  0.238968
11 -0.450857 -0.011133 -0.175746  0.236166  0.263251 -0.314844
12  0.040238 -1.009204 -0.496517  0.229299  0.448032  0.004939
13  3.233730 -0.374580 -0.495373 -0.521238 -0.639295 -0.090048
14 -2.236265 -0.371793 -0.398994  0.406966 -0.416761  0.050619
15  5.172992  0.779915 -0.385912 -0.232212  0.179287 -0.030905
16 -1.699644 -0.305597  0.318508 -0.297463 -0.163425  0.114423
17  4.578146 -0.347591  1.499642 -0.454252 -0.191142  0.104149
18  0.822603 -0.698906  1.427811  0.760779  0.184260 -0.251103
19 -0.097762  0.650446  0.100508 -0.500097  0.487218  0.219242
20  1.963183 -0.224768 -0.255881 -0.048474  0.822746  0.152247
21 -0.542289 -0.079589 -0.305393  0.131699  0.052740 -0.036726
22  0.532221 -1.017167 -0.423716  0.169536  0.357813 -0.066099
23  3.548697  0.778462 -0.449363  0.323679 -0.358333 -0.077456
24 -2.305900 -0.117704  0.253989 -0.516183  0.055894 -0.010793

In [32]:
# add columns
pca_data.columns = "comp0","comp1","comp2","comp3","comp4","comp5"
pca_data

       comp0     comp1     comp2     comp3     comp4     comp5
0  -1.009874 -1.064310  0.081066  0.056951 -0.128754 -0.034650
1  -2.822238  2.259045  0.836829  0.143845 -0.125962 -0.180703
2   1.112466  1.631209 -0.266787  1.075075 -0.191814  0.345679
3  -0.741741 -0.042187  0.060501 -0.157208 -0.577611  0.109163
4  -0.311912 -0.635244  0.010241  0.171364  0.012726 -0.016921
5  -1.696691 -0.344363 -0.253408  0.012564 -0.052661 -0.027166
6  -1.246821 -0.490984 -0.032094 -0.205644  0.293505 -0.078012
7  -0.338750 -0.785169 -0.493585  0.039856 -0.544979 -0.155372
8  -2.374150 -0.386539  0.116098 -0.453366 -0.230108  0.266984
9  -1.403277  2.119515 -0.442827 -0.632543  0.230054 -0.235615
10 -1.726103  0.088237  0.170404  0.260902  0.233318  0.238968
11 -0.450857 -0.011133 -0.175746  0.236166  0.263251 -0.314844
12  0.040238 -1.009204 -0.496517  0.229299  0.448032  0.004939
13  3.233730 -0.374580 -0.495373 -0.521238 -0.639295 -0.090048
14 -2.236265 -0.371793 -0.398994  0.406966 -0.416761  0.050619
15  5.172992  0.779915 -0.385912 -0.232212  0.179287 -0.030905
16 -1.699644 -0.305597  0.318508 -0.297463 -0.163425  0.114423
17  4.578146 -0.347591  1.499642 -0.454252 -0.191142  0.104149
18  0.822603 -0.698906  1.427811  0.760779  0.184260 -0.251103
19 -0.097762  0.650446  0.100508 -0.500097  0.487218  0.219242
20  1.963183 -0.224768 -0.255881 -0.048474  0.822746  0.152247
21 -0.542289 -0.079589 -0.305393  0.131699  0.052740 -0.036726
22  0.532221 -1.017167 -0.423716  0.169536  0.357813 -0.066099
23  3.548697  0.778462 -0.449363  0.323679 -0.358333 -0.077456
24 -2.305900 -0.117704  0.253989 -0.516183  0.055894 -0.010793

In [33]:
final = pd.concat([Dataset.Univ, pca_data.iloc[:,:3]], axis = 1)

In [34]:
final

            Univ     comp0     comp1     comp2
0          Brown -1.009874 -1.064310  0.081066
1        CalTech -2.822238  2.259045  0.836829
2            CMU  1.112466  1.631209 -0.266787
3       Columbia -0.741741 -0.042187  0.060501
4        Cornell -0.311912 -0.635244  0.010241
5      Dartmouth -1.696691 -0.344363 -0.253408
6           Duke -1.246821 -0.490984 -0.032094
7     Georgetown -0.338750 -0.785169 -0.493585
8        Harvard -2.374150 -0.386539  0.116098
9   JohnsHopkins -1.403277  2.119515 -0.442827
10           MIT -1.726103  0.088237  0.170404
11  Northwestern -0.450857 -0.011133 -0.175746
12     NotreDame  0.040238 -1.009204 -0.496517
13     PennState  3.233730 -0.374580 -0.495373
14     Princeton -2.236265 -0.371793 -0.398994
15        Purdue  5.172992  0.779915 -0.385912
16      Stanford -1.699644 -0.305597  0.318508
17      TexasA&M  4.578146 -0.347591  1.499642
18    UCBerkeley  0.822603 -0.698906  1.427811
19      UChicago -0.097762  0.650446  0.100508
20     UMichigan  1.963183 -0.224768 -0.255881
21         UPenn -0.542289 -0.079589 -0.305393
22           UVA  0.532221 -1.017167 -0.423716
23    UWisconsin  3.548697  0.778462 -0.449363
24          Yale -2.305900 -0.117704  0.253989